from __future__ import annotations

from pathlib import Path


FILES: list[str] = [
    "README.md",
    "docs/README.md",
    "docs/getting-started.md",
    "docs/api.md",
    "docs/faq.md",
    "docs/visualflow.md",
    "docs/web-editor.md",
    "docs/cli.md",
    "docs/architecture.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "ACKNOWLEDMENTS.md",
]


def _build() -> str:
    missing = [f for f in FILES if not Path(f).exists()]
    if missing:
        raise FileNotFoundError(f"Missing files: {missing}")

    out: list[str] = []
    out.append("# AbstractFlow (Full Context)")
    out.append("")
    out.append(
        "> Generated file: concatenated docs for offline/agentic consumption. "
        "Prefer `llms.txt` as an index and treat the original files as source of truth."
    )
    out.append("")
    out.append("Generated by: `scripts/generate_llms_full.py`")
    out.append("")
    out.append("Included files (repo-root relative):")
    out.extend([f"- {f}" for f in FILES])
    out.append("")

    for f in FILES:
        out.append("---")
        out.append(f"file: {f}")
        out.append("---")
        out.append("")
        content = Path(f).read_text(encoding="utf-8")
        out.append(content.rstrip())
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    Path("llms-full.txt").write_text(_build(), encoding="utf-8")


if __name__ == "__main__":
    main()
